'use client'
import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'


// importing aos
import AOS from 'aos';
import 'aos/dist/aos.css';
import { useEffect } from 'react';
import SEO from '@/components/SEO/SEO';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children  }) {
   // aos
   useEffect(() => {
    
    AOS.init();
  }, [])

  return (
    <html lang="en">
      <head>
        <SEO/>
      </head>
      <body className={inter.className}>
      <div className="lg:grid h-screen lg:grid-cols-[20%_1fr] ">
    <div className="">
    <Navbar />
    {/* <div className='sm:w-full sm:h-0.5 md:w-full md:h-0.5 lg:w-0.5 lg: bg-[#555555]'></div> */}
    </div>
    <div className='bg-black  lg:overflow-y-auto' >
    {children}
    </div>
  </div>
      </body>
    </html>
  )
}
